[workspace]

members = [
    "rustHello",
    "macro_export",
    "visibilitytest",
    "featuresample",
    "httpie",
    "thumbor",
    "queryer",
    "implfortuples",
    "syncmacro",
    "asynctokio",
    "bs58test",
    'turbofish_demo',
]


[profile.release]
panic = 'unwind'