[package]
name = "syncmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true   # 使用过程宏

[dependencies]
quote = "1.0.9"                 # 目前没用到，先注释了
proc-macro2 = "1.0.27"
syn = {version="1.0.72", features=["full"]}


[dependencies.hex-literal]
version = '0.3.1'