version: '3'

# username: postgres, password: postgres
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres