[package]
name = "no_std_formatter"
version = "0.1.0"
edition = "2021"
description = '演示在no_std下的 format!， 本质核心是no_std没有内存分配器，必须自己手动处理。'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
